### ISSUE TITLE
PHP 8 version isn't support

### ISSUE THREAD

**Issue by volodymyr-chudovskyi** [muhdfaiz/laravel-tail-db#2]
I try to install your package in the project where I use php 8 version. 
I got a following error:
```
 [InvalidArgumentException]                                                                                                       
  Package muhdfaiz/laravel-tail-db has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version:  
    - muhdfaiz/laravel-tail-db requires php ^7.0 which does not match your installed version 8.0.8.                                
    - muhdfaiz/laravel-tail-db requires react/socket ^1.6 but it is not present.                                                   
    - muhdfaiz/laravel-tail-db requires react/event-loop ^1.1 but it is not present.  
```
I made a Pull Request to solve this problem https://github.com/muhdfaiz/laravel-tail-db/pull/1
Could you please to approve that Pull Request or solve this problem by yourself?

**Comment by muhdfaiz** [comment]
I already merged your pull request. Thank you for your contribution.

I already changed to support PHP8 but haven't push and release yet because want to complete the desktop app. 

The desktop app I think I will release 1 or 2 weeks from now.

![](https://i.ibb.co/hX72Pzb/Screenshot-2021-10-05-at-6-50-46-PM.png?raw=true)
